name: Git create tag

on:
  workflow_dispatch:

env:
  TAG: 0.1.0

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
          caCertificate: ${{ secrets.VAULTCA }}
          secrets: |
            ci/data/gh-workflows/deployment-status slack-webhook-url | SLACK_WEBHOOK_URL;

      - uses: actions/checkout@master

      - name: Set user data
        run: |
          git config --global user.email "admin@danubetech.com"
          git config --global user.name "Github Workflow"

      - name: Create tag
        run: git tag -a "v${{ env.TAG }}" -m "[skip ci] Release tag v${{ env.TAG }}"

      - name: Push tag
        run: git push origin "v${{ env.TAG }}"

      - name: Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
        if: failure()
