name: Publish image to dockerhub

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Docker Build and Push
        uses: danubetech/github-action-docker-build-push@master
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKER_FILE: docker/Dockerfile
          CONTAINER_TAG: universalregistrar/driver-did-btcr:latest
